name: WorkLabs
options:
  deploymentTarget:
    macOS: "15.2"
settings:
  base:
    CLANG_ENABLE_OBJC_ARC: YES
    PRODUCT_NAME: WorkLabs
targets:
  WorkLabs:
    type: application
    platform: macOS
    sources:
      - WorkLabs
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tvunetworks.partyline
      DEVELOPMENT_TEAM: YDEVQQ22JR
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: Apple Development
    info:
      path: WorkLabs/Info.plist
      properties:
        NSMainStoryboardFile: Main
    entitlements:
      path: WorkLabs/WorkLabs.entitlements
