# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OBSLabs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ffmpeg-kit-local', :path => '../../LocalPodspecs/ffmpeg-kit-macos-full/'

end
